config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    resources :posts
    resources :projects
    resources :contacts, only: [:new, :create]
    get 'welcome/index'
    root 'welcome#index'
    get '*path' =>redirect('/')

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha  => true

  def headers
  	{
	  	:subject => "Contact Form",
	  	:to => "aama.79@gmail.com",
	  	:from => %("#{name}" <#{email}>)
	  }
	end
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title,  presence: true, uniqueness: true
  	validates :content, presence: true, length: { minimum: 25 }
    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :title,  presence: true, uniqueness: true
  	validates :description, presence: true, length: { minimum: 25 }
  	validates :link, presence: true
	extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
		@contact = Contact.new
	end
	def create
		@contact = Contact.new(params[:contact])
    	@contact.request = request
    	if @contact.deliver
      	flash.now[:error] = nil
    	else
      	flash.now[:error] = 'Cannot send message.'
      	render :new
    	end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    def index
        @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 4)
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new post_params
        if @post.save
            redirect_to @post, notice: "Tu articulo fue guardado satisfactoriamente!"
        else
            render 'new', notice: "No se pudo guardar tu articulo!"
        end
    end

    def show
        
    end
    def edit

    end

    def update 
        if @post.update post_params
            redirect_to @post, notice: "Tu articulo fue guardado exitosamente!"
        else
            render 'edit'
        end

    end
    def destroy
        @post.destroy
        redirect_to post_path
    end
    private
    
    def post_params
        params.require(:post).permit(:title, :content, :slug)
    end

    def find_post
        @post = Post.friendly.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@projects = Project.all.order("created_at desc")
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new project_params
		if @project.save
			redirect_to @project, notice: "Muy bien Angel! El proyecto fue exsitosamente guardado!"
		else
			render 'new'
		end
	end
	def show
		
	end
	def edit
		
	end
	def update
		if @project.update project_params
			redirect_to @project, notice: "Muy bien Angel! El proyecto fue exsitosamente guardado!"
		else
			render 'edit'
		end
	end
	def destroy
		@project.destroy
		redirect_to @projects_path
	end

	private

	def find_project
		@project = Project.friendly.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:title, :description, :link, :slug)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@posts = Post.all.limit(3).order("created_at desc")
		@projects = Project.all.limit(3).order("created_at desc")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
      		no_intra_emphasis: true,
      		disable_indented_code_blocks: true,
      		fenced_code_blocks: true,
      		lax_html_blocks: true,
      		strikethrough: true,
      		superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<h1>Gracias por tu mensaje!!</h1>
	<p>Te respondere lo mas pronto posible.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page_title">Say Hello!</h1>

<div class="skinny_wrapper wrapper_padding">
	<%= form_for @contact do |f| %>
		<%= f.label :name, "Nombre" %><br>
		<%= f.text_field :name, required: true %>

		<br>

		<%= f.label :email %><br>
		<%= f.email_field :email, required: true %>

		<br>

		<%= f.label :message, "Mensaje" %><br>
		<%= f.text_area :message, as: :text %>

		<div class="hidden">
			<%= f.label :nickname %><br>
			<%= f.text_field :nickname, hint: 'deja este mensaje en blanco' %>
		</div>

		<%= f.submit 'Enviar Mensaje', class: "button" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Angel A. Martinez Blog Personal, Fotografia, Desarrollo Web y algo mas...</title>
	<link href='https://fonts.googleapis.com/css?family=Lora:400,700' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<header id="main_navegation" class="clearfix">
		<%= link_to "Angel A. Martinez A.", root_path, class:"name" %>
		<nav>
			<%= link_to "Articulos", posts_path %>
			<%= link_to "Proyectos", projects_path %>
			<%= link_to "Contacto", new_contact_path %>
			<% if user_signed_in? %>
				<%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %>
			<% end %>
		</nav>
	</header>
	<% if notice %>
		<p class="notice"><%= notice %></p>
	<% elsif %>
    	<p class="alert"><%= alert %></p>
    <% end %>
<%= yield %>
 <footer id="main_footer">
		<p class="copyright">&copy 2016 Angel A. Martinez A.</p>
		<nav>
			<a href="https://twitter.com/aama79" target="_blank"><i class="fa fa-twitter"></i></a>
			<a href="https://github.com/aama79" target="_blank"><i class="fa fa-github"></i></a>
			<a href="https://www.instagram.com/aama.79/" target="_blank"><i class="fa fa-instagram"></i></a>
			<a href="https://www.flickr.com/photos/parivrajaka/" target="_blank"><i class="fa fa-flickr"></i></a>
		</nav>
	</footer>
</body>
</html>

app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
    /* * * Configuracion de Variables * * */
    var disqus_shortname = 'blogpersonal';
    var disqus_identifier = '<%= @post.id%>';
    var disqus_title = '<%= @post.title %>';
    var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';
    
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//aama79.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	<h2><%= pluralize(@post.errors.count, "error") %> no se puede guardar este articulo: </h2>
	<ul>
		<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>

	<%= f.label :title, "Titulo" %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :content, "Escribe tu articulo aqui!" %><br>
	<%= f.text_area :content %>

	<br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1 id="page_title">Editar Articulo</h1>

<div class="skinny_wrapper wrapper_paddin">
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1 id="page_title">Cosas que Comparto</h1>
	<% if user_signed_in? %>
		<div id="admin_link">
			<%= link_to "Crear nuevo Aritculo", new_post_path %>
		</div>
	<% end %>
<div id="post_wrapper" class="skinny_wrapper">
    <% @posts.each do |post| %>
     <div class="post">
         <p class="date"><%= post.created_at.strftime('%b %d, %Y')%></p>
         <h2><a href="#"><%= link_to post.title, post %></a></h2>
		<hr>
     </div>
    <% end %>
</div>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1 id="page_title">Nuevo Articulo</h1>

<div class="skinny_wrapper wrapper_paddin">
	<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
			<header>
				<p class="date"><%= @post.created_at.strftime('%A, %b %d') %></p>
				<h1><%= @post.title%></h1>
				<hr>
			</header>
			<div id="content">
				<%= markdown @post.content%>
			</div>

			<% if user_signed_in? %>
				<div id="admin_link">
					<%= link_to "Editar", edit_post_path(@post) %>
					<%= link_to "Eliminar", post_path(@post), method: :delete, data: {confirm: "¿Estas seguro de eliminar este Aritculo?"}%>
				</div>
			<% end %>

			<hr>
			<div id="share_box">
				<p>Compartir Aritculo en</p>
				<!-- Twitter -->
    			<a onclick="javascript:window.open('http://twitter.com/share?text=<%= @post.title %> by @aama79 - &amp;url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
    			<i class="fa fa-twitter"></i></a>
    			<!-- Facebook -->
    			<a onclick="javascript:window.open('https://www.facebook.com/sharer.php?id=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
    			<i class="fa fa-facebook"></i></a>
    			<!-- Google Plus -->
    			<a onclick="javascript:window.open('https://plus.google.com/share?url=<%= url_for([@post, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);">
    			<i class="fa fa-google-plus"></i></a>
	
			</div>
			<hr>

			
			<hr>
    	<%= render 'disqus'%>
		</div>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	<% if @project.errors.any? %>
	<h2><%= pluralize(@project.errors.count, "error") %> no se puede guardar este projecto: </h2>
	<ul>
		<% @project.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>

	<%= f.label :title, "Titulo" %><br>
	<%= f.text_field :title %>

	<br>
	<br>

	<%= f.label :description, "Escribe tu projecto aqui!" %><br>
	<%= f.text_area :description %>

	<br>
	<br>

	<%= f.label :link, "Enlace" %><br>
	<%= f.text_field :link %>

	<br>
	<br>
	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1 id="page_title">Editar Proyecto</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page_title">Cosas que hecho!</h1>
<% if user_signed_in? %>
	<div id="admin_link">
		<%= link_to "Crear nuevo Proyecto", new_project_path %>
	</div>
<% end %>
<div id="post_wrapper" class="skinny_wrapper">
    <% @projects.each do |project| %>
     <div class="post">
         <p class="date"><%= project.created_at.strftime('%b %d, %Y')%></p>
         <h2><a href="#"><%= link_to project.title, project %></a></h2>
		<hr>
     </div>
    <% end %>
</div>

app/views/projects/new.html.erb
<h1 id="page_title">Nuevo Proyecto</h1>
<div class="skinny_wrapper wrapper_padding">
	<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny_wrapper wrapper_padding">
	<header>
		<p class="date"><%= @project.created_at.strftime('%A, %b %d') %></p>
		<h1><%= @project.title%></h1>
		<hr>
	</header>
		<div id="content">
		<%= markdown @project.description %>
		</div>
		<div class="button_wrapper">
			<a href="<%= @project.link %>" class="project_button" target="_blank">Entra en <%= @project.title %></a>
		</div>
		
	<% if user_signed_in? %>
		<div id="admin_link">
		<%= link_to "Editar", edit_project_path(@project) %>
		<%= link_to "Eliminar",  project_path(@project), method: :delete, data: {confirm: "¿Estas seguro de Eliminar este Proyecto?"} %>
		</div>
	<% end %>
	<hr>
</div>


app/views/welcome/index.html.erb
<div class="wrapper wrapper_padding clearfix">
		<div class="col-1 about homepage_content">
			<h2>Acerca de mi...</h2>
			<hr>
			<p>Soy un gran aficionado de la fotografia, vivo en Venezuea</p>
			<p>Durante el dia hago diferentes actividades como: Ejercicios Funcionales, Leer blog, libros de diferentes temas, y Fotografia</p>
			<p>Siempre estoy en constante actividad y en busca de aprender nuevas cosas.</p>
			<p>Por la noche me dedico al desarrollo de aplicaciones web usando Ruby, CSS3, JavaScript, HTML5</p>
			<p>Pudes seguirme en mis redes sociales <a href="https://twitter.com/aama79">Twitter</a>, <a href="https://instagram.com/aama.79">Instagram</a>, <a href="https://www.flickr.com/photos/parivrajaka">Flick</a> y comparto algo de codigo en <a href="https://github.com/aama79">GitHub</a>.</p>
		</div>
		<div class="col-2 homepage_content">
			<h2>Cosas que Comparto</h2>
			<hr>
			<% @posts.each do |post| %>
				<h3><a href="#"><%= link_to post.title, post %></a></h3>
				<p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
			<% end %>
		</div>
		<div class="col-3 homepage_content">
			<h2>Logros</h2>
			<hr>
			<% @projects.each do |project| %>
				<h3><a href="#"><%= link_to project.title, project %></a></h3>
				<p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
			<% end %>
		</div>
	</div>